# Generated by Django 5.2.7 on 2025-10-07 17:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('ready', 'Ready'), ('processing', 'Processing'), ('error', 'Error')], default='creating', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('feature_columns', models.JSONField(default=list, help_text='Lista de colunas usadas como features')),
                ('target_column', models.CharField(max_length=100)),
                ('epochs', models.IntegerField(default=100)),
                ('batch_size', models.IntegerField(default=32)),
                ('test_size', models.FloatField(default=0.2)),
                ('keras_model_file', models.FileField(blank=True, help_text='Arquivo .h5 do modelo Keras', null=True, upload_to='models/%Y/%m/%d/')),
                ('tflite_model_file', models.FileField(blank=True, help_text='Arquivo .tflite para dispositivos embarcados', null=True, upload_to='models/%Y/%m/%d/')),
                ('scaler_file', models.FileField(blank=True, help_text='Arquivo .pkl do scaler', null=True, upload_to='models/%Y/%m/%d/')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('training_history', models.JSONField(blank=True, default=dict)),
                ('confusion_matrix', models.JSONField(blank=True, default=dict)),
                ('classification_report', models.JSONField(blank=True, default=dict)),
                ('model_size_kb', models.FloatField(blank=True, null=True)),
                ('training_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='studio.project')),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='datasets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'csv'])])),
                ('file_type', models.CharField(choices=[('txt', 'Text File'), ('csv', 'CSV File')], max_length=3)),
                ('delimiter', models.CharField(default=',', max_length=5)),
                ('target_label', models.CharField(blank=True, help_text="Label para esta classe (ex: 'ligado', 'defeito')", max_length=100, null=True)),
                ('has_target_column', models.BooleanField(default=False, help_text='Se True, o arquivo já contém a coluna target')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows_count', models.IntegerField(blank=True, null=True)),
                ('columns', models.JSONField(blank=True, default=dict, help_text='Metadados das colunas do arquivo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='studio.project')),
            ],
            options={
                'verbose_name': 'Data File',
                'verbose_name_plural': 'Data Files',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
