# Generated by Django 5.2.9 on 2025-12-02 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('localizacao', models.CharField(help_text='Ex: Setor A, Esteira 2', max_length=100)),
                ('uid_hardware', models.CharField(help_text='ID do ESP', max_length=50, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eixo_x', models.FloatField(default=0.0, help_text='Eixo X')),
                ('eixo_y', models.FloatField(default=0.0, help_text='Eixo Y')),
                ('eixo_z', models.FloatField(default=0.0, help_text='Eixo Z')),
                ('rpm', models.FloatField(default=0.0, help_text='RPM')),
                ('em_falha', models.BooleanField(default=False)),
                ('data_leitura', models.DateTimeField(auto_now_add=True)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='motores.motor')),
            ],
        ),
    ]
