# Generated by Django 5.1.3 on 2025-12-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leitura',
            options={'ordering': ['-data_leitura']},
        ),
        migrations.AlterField(
            model_name='leitura',
            name='em_falha',
            field=models.IntegerField(default=0),
        ),
    ]
